name: Tests
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - name: Setup GHC
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 8.8.4
          enable-stack: true

      - name: Clone project
        uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path:
            | # Exclude due to build failure on OS X, per https://github.com/commercialhaskell/stack/issues/5405
            ~/.stack
            !~/.stack/setup-exe-cache
          key: ${{ runner.os }}-${{ hashFiles('stack.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Build and run tests
        run: "stack test --fast --no-terminal --system-ghc"
